// Code generated by protoc-gen-go. DO NOT EDIT.
// source: general.proto

// Those are belong to `protobuf` packet

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Header 是用來包裝其他協議的標頭檔
// uuid : 封包識別碼，由 client 產生，格式為
//        username,month+day+time+second,00000(16進位)
//        16^5 除以一秒一個請求可用 728 天
// contain : 實際封包內容
type Header struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// Types that are valid to be assigned to Contain:
	//	*Header_HeartBeat
	//	*Header_SetNameReq
	//	*Header_MessageReq
	//	*Header_MessageNotify
	Contain              isHeader_Contain `protobuf_oneof:"contain"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_a913b1a5d8940539, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Header) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type isHeader_Contain interface {
	isHeader_Contain()
}

type Header_HeartBeat struct {
	HeartBeat *HeartBeat `protobuf:"bytes,3,opt,name=heartBeat,proto3,oneof"`
}

type Header_SetNameReq struct {
	SetNameReq *SetNameReq `protobuf:"bytes,4,opt,name=setNameReq,proto3,oneof"`
}

type Header_MessageReq struct {
	MessageReq *MessageReq `protobuf:"bytes,5,opt,name=messageReq,proto3,oneof"`
}

type Header_MessageNotify struct {
	MessageNotify *MessageNotify `protobuf:"bytes,6,opt,name=messageNotify,proto3,oneof"`
}

func (*Header_HeartBeat) isHeader_Contain() {}

func (*Header_SetNameReq) isHeader_Contain() {}

func (*Header_MessageReq) isHeader_Contain() {}

func (*Header_MessageNotify) isHeader_Contain() {}

func (m *Header) GetContain() isHeader_Contain {
	if m != nil {
		return m.Contain
	}
	return nil
}

func (m *Header) GetHeartBeat() *HeartBeat {
	if x, ok := m.GetContain().(*Header_HeartBeat); ok {
		return x.HeartBeat
	}
	return nil
}

func (m *Header) GetSetNameReq() *SetNameReq {
	if x, ok := m.GetContain().(*Header_SetNameReq); ok {
		return x.SetNameReq
	}
	return nil
}

func (m *Header) GetMessageReq() *MessageReq {
	if x, ok := m.GetContain().(*Header_MessageReq); ok {
		return x.MessageReq
	}
	return nil
}

func (m *Header) GetMessageNotify() *MessageNotify {
	if x, ok := m.GetContain().(*Header_MessageNotify); ok {
		return x.MessageNotify
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Header) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Header_HeartBeat)(nil),
		(*Header_SetNameReq)(nil),
		(*Header_MessageReq)(nil),
		(*Header_MessageNotify)(nil),
	}
}

// HeartBeat 心跳包
type HeartBeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_a913b1a5d8940539, []int{1}
}

func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (m *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(m, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

// SetNameReq 設定名稱
type SetNameReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNameReq) Reset()         { *m = SetNameReq{} }
func (m *SetNameReq) String() string { return proto.CompactTextString(m) }
func (*SetNameReq) ProtoMessage()    {}
func (*SetNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a913b1a5d8940539, []int{2}
}

func (m *SetNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNameReq.Unmarshal(m, b)
}
func (m *SetNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNameReq.Marshal(b, m, deterministic)
}
func (m *SetNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNameReq.Merge(m, src)
}
func (m *SetNameReq) XXX_Size() int {
	return xxx_messageInfo_SetNameReq.Size(m)
}
func (m *SetNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetNameReq proto.InternalMessageInfo

func (m *SetNameReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

// MessageReq 訊息請求
type MessageReq struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReq) Reset()         { *m = MessageReq{} }
func (m *MessageReq) String() string { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()    {}
func (*MessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a913b1a5d8940539, []int{3}
}

func (m *MessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReq.Unmarshal(m, b)
}
func (m *MessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReq.Marshal(b, m, deterministic)
}
func (m *MessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReq.Merge(m, src)
}
func (m *MessageReq) XXX_Size() int {
	return xxx_messageInfo_MessageReq.Size(m)
}
func (m *MessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReq proto.InternalMessageInfo

func (m *MessageReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// MessageNotify 訊息廣播
type MessageNotify struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageNotify) Reset()         { *m = MessageNotify{} }
func (m *MessageNotify) String() string { return proto.CompactTextString(m) }
func (*MessageNotify) ProtoMessage()    {}
func (*MessageNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a913b1a5d8940539, []int{4}
}

func (m *MessageNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageNotify.Unmarshal(m, b)
}
func (m *MessageNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageNotify.Marshal(b, m, deterministic)
}
func (m *MessageNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageNotify.Merge(m, src)
}
func (m *MessageNotify) XXX_Size() int {
	return xxx_messageInfo_MessageNotify.Size(m)
}
func (m *MessageNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageNotify.DiscardUnknown(m)
}

var xxx_messageInfo_MessageNotify proto.InternalMessageInfo

func (m *MessageNotify) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *MessageNotify) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Header)(nil), "protobuf.Header")
	proto.RegisterType((*HeartBeat)(nil), "protobuf.HeartBeat")
	proto.RegisterType((*SetNameReq)(nil), "protobuf.SetNameReq")
	proto.RegisterType((*MessageReq)(nil), "protobuf.MessageReq")
	proto.RegisterType((*MessageNotify)(nil), "protobuf.MessageNotify")
}

func init() { proto.RegisterFile("general.proto", fileDescriptor_a913b1a5d8940539) }

var fileDescriptor_a913b1a5d8940539 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x93, 0xd0, 0xa6, 0xcd, 0x55, 0x59, 0x0c, 0x12, 0x16, 0x53, 0xe4, 0x01, 0x65, 0xca,
	0x40, 0x25, 0x56, 0xa4, 0x4a, 0x48, 0x5e, 0xe8, 0x60, 0x9e, 0xc0, 0x6d, 0xae, 0x25, 0x12, 0x89,
	0xc1, 0x71, 0x06, 0x1e, 0x87, 0x37, 0x45, 0x31, 0x89, 0x9d, 0x80, 0xd4, 0xc9, 0x77, 0xfe, 0xff,
	0xef, 0xf7, 0x9d, 0x21, 0x3d, 0x63, 0x83, 0x5a, 0xbe, 0x17, 0x1f, 0x5a, 0x19, 0x45, 0xd6, 0xf6,
	0x38, 0x74, 0x27, 0xf6, 0x1d, 0x41, 0xcc, 0x51, 0x96, 0xa8, 0x09, 0x81, 0x45, 0xd7, 0x55, 0x25,
	0x0d, 0xb3, 0x30, 0x4f, 0x84, 0xad, 0xfb, 0xbb, 0xa3, 0x2a, 0x91, 0x46, 0x59, 0x98, 0x2f, 0x85,
	0xad, 0xc9, 0x16, 0x92, 0x37, 0x94, 0xda, 0xec, 0x50, 0x1a, 0x7a, 0x95, 0x85, 0xf9, 0xe6, 0xe1,
	0xba, 0x18, 0x03, 0x0b, 0x3e, 0x4a, 0x3c, 0x10, 0xde, 0x47, 0x1e, 0x01, 0x5a, 0x34, 0x7b, 0x59,
	0xa3, 0xc0, 0x4f, 0xba, 0xb0, 0xd4, 0x8d, 0xa7, 0x5e, 0x9d, 0xc6, 0x03, 0x31, 0x71, 0xf6, 0x5c,
	0x8d, 0x6d, 0x2b, 0xcf, 0x96, 0x5b, 0xfe, 0xe5, 0x5e, 0x9c, 0xd6, 0x73, 0xde, 0x49, 0x9e, 0x20,
	0x1d, 0xba, 0xbd, 0x32, 0xd5, 0xe9, 0x8b, 0xc6, 0x16, 0xbd, 0xfd, 0x87, 0xfe, 0xca, 0x3c, 0x10,
	0x73, 0xff, 0x2e, 0x81, 0xd5, 0x51, 0x35, 0x46, 0x56, 0x0d, 0xdb, 0x40, 0xe2, 0xb6, 0x62, 0x39,
	0x80, 0x1f, 0x96, 0xdc, 0xc1, 0xba, 0x6b, 0x51, 0x37, 0xb2, 0xc6, 0xe1, 0xdf, 0x5c, 0xcf, 0xee,
	0x01, 0xfc, 0x78, 0x84, 0xc2, 0x6a, 0x78, 0x60, 0x30, 0x8e, 0x2d, 0x7b, 0x86, 0x74, 0x36, 0xcb,
	0xa5, 0xd0, 0x69, 0x4c, 0x34, 0x8b, 0x39, 0xc4, 0x76, 0xb3, 0xed, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0x5e, 0x1d, 0x8b, 0xeb, 0x01, 0x00, 0x00,
}
